#!/bin/sh

#disable autoload
sed -i '/x86_adapt_defs/d' /etc/modules
sed -i '/x86_adapt_driver/d' /etc/modules

#remove from dkms
dkms uninstall -m x86_adapt_driver -v ###VERSION###
dkms uninstall -m x86_adapt_defs -v ###VERSION###

dkms remove -m x86_adapt_driver -v ###VERSION### --all
dkms remove -m x86_adapt_defs -v ###VERSION### --all
